### ISSUE TITLE
how to set the posts count per page?

### ISSUE THREAD

**Issue by luckypoem** [jd/julien.danjou.info#10]
hi.
i setup a blog as per ur repo,but how to set the posts count per page?
i checked site.yaml,found nothing.

**Comment by jd** [comment]
Hi @luckypoem,

It would have been better to shoot a mail rather than open an issue, since well, it's not an issue, but he.

What do you call the post count exactly?

**Comment by luckypoem** [comment]
i mean quantity,posts quantity per page,

**Comment by luckypoem** [comment]
yours is 10, i want to set it to be 3

**Comment by jd** [comment]
Check `layout/macros.j2`.
