### ISSUE TITLE
How to run it with hyde?

### ISSUE THREAD

**Issue by vonpupp** [jd/julien.danjou.info#6]
Dear Julien,

Congratulations on your work. I use awesome-wm and I'm now trying Hyde for my first time. Your work is inspiring!

I'm trying to test hyde with your website but it doesn't seem to run properly. I installed the Makefile's dependencies: `pngcrush`.

When I run `make` I get the following error:

```
(bin2)[av:~/hyde-test/julien.danjou.info]$ make                                                                                                                                                           (master✱) 
rm -rf deploy
rm -rf content/blog/tags
hyde -x gen
 10:00:22 hyde.engine Reading site configuration from [/home/av/hyde-test/julien.danjou.info/site.yaml]
 10:00:22 hyde.engine Reading site contents
 10:00:22 hyde.engine Generating site at [/home/av/hyde-test/julien.danjou.info]
 10:00:22 hyde.engine Configuring the template environment
 10:00:23 hyde Error occured when calling paginator
Traceback (most recent call last):
  File "/home/av/.venv/bin2/bin/hyde", line 11, in <module>
    sys.exit(main())
  File "/home/av/.venv/bin2/lib/python2.7/site-packages/hyde/main.py", line 10, in main
    Engine().run()
  File "/home/av/.venv/bin2/lib/python2.7/site-packages/commando/application.py", line 305, in run
    args.run(self, args)
  File "/home/av/.venv/bin2/lib/python2.7/site-packages/hyde/engine.py", line 101, in gen
    gen.generate_all(incremental=incremental)
  File "/home/av/.venv/bin2/lib/python2.7/site-packages/hyde/generator.py", line 210, in generate_all
    self.events.begin_site()
  File "/home/av/.venv/bin2/lib/python2.7/site-packages/hyde/plugin.py", line 72, in __call_plugins__
    plugin.plugin_name, sys.exc_info())
  File "/home/av/.venv/bin2/lib/python2.7/site-packages/hyde/plugin.py", line 68, in __call_plugins__
    res = function(*args)
  File "/home/av/.venv/bin2/lib/python2.7/site-packages/hyde/ext/plugins/structure.py", line 326, in begin_site
    for resource in paged_resources:
  File "/home/av/.venv/bin2/lib/python2.7/site-packages/hyde/ext/plugins/structure.py", line 325, in <genexpr>
    if hasattr(res.meta, 'paginator'))
hyde.exceptions.HydeException: Error occured when calling paginator
Makefile:16: recipe for target 'deploy' failed
make: *** [deploy] Error 1
```

If I run `hyde -x gen` I get no error however when I `hyde serve`, I only get an HTML directory listing of the files, and the hyde log is:

```
(bin2)[av:~/hyde-test/julien.danjou.info]$ hyde serve                                                                                                                                                     (master✱) 
 10:03:46 hyde.engine Reading site configuration from [/home/av/hyde-test/julien.danjou.info/site.yaml]
 10:03:47 hyde Starting webserver at [localhost]:[8080]
 10:03:54 hyde.server Cannot load file: []
127.0.0.1 - - [10/Oct/2015 10:03:54] "GET / HTTP/1.1" 200 -
 10:03:56 hyde.server Cannot load file: []
127.0.0.1 - - [10/Oct/2015 10:03:56] "GET / HTTP/1.1" 200 -
```

Could you please help me out? I found your layout very beautiful and I would like to reproduce something similar for my personal website.

Thank you very much.

**Comment by jd** [comment]
It's possible that it only works with Hyde from the master branch. Did you try it?

**Comment by vonpupp** [comment]
Thanks for your reply Julien,

I installed Hyde via pip. I imagine that it is the same master branch but I
will create a new virtualenv and try the git master branch directly. Would
it be possible you to pip freeze your environment and send me the
requirements file?

Your personal website repository is totally open and it is can be deployed
for testing purposes or it needs any personal/private dependency?

On Sat, Oct 10, 2015 at 11:51 AM, Julien Danjou notifications@github.com
wrote:

> It's possible that it only works with Hyde from the master branch. Did you
> try it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jd/julien.danjou.info/issues/6#issuecomment-147094895
> .

## 

Albert.

**Comment by jd** [comment]
The Hyde on pip is 2 years old. Hyde development has been stopped for a while and just restarted a few weeks ago. You really need to install it using git.

As far as I can tell, you don't need anything private to deploy it. I'll update the requirements file.

**Comment by vonpupp** [comment]
Thank you very much Julien,

I could it get it running without the errors using `make web` however the result is still the same, it only renders the directory listing. Any ideas? I'm using Arch Linux and Hyde 0.8.9a from the requirements file you commited.

Herewith the log:

```
(.julien2)[av:~/hyde-test/julien.danjou.info]$ make web                                                                                                                                                   (master✱) 
rm -rf deploy
rm -rf content/blog/tags
hyde -x gen
 15:28:56 hyde.engine Reading site configuration from [/home/av/hyde-test/julien.danjou.info/site.yaml]
 15:28:56 hyde.engine Reading site contents
 15:28:56 hyde.engine Generating site at [/home/av/hyde-test/julien.danjou.info]
 15:28:56 hyde.engine Configuring the template environment
 15:28:57 hyde.engine Generating site to [/home/av/hyde-test/julien.danjou.info/deploy]
 15:29:34 hyde Generation complete.
cd deploy && python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [10/Oct/2015 15:30:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2015 15:30:08] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2015 15:30:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2015 15:30:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2015 15:30:16] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2015 15:30:16] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2015 15:30:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2015 15:30:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2015 15:30:29] "GET /favicon.ico HTTP/1.1" 200 -
```

Thank you very much.

**Comment by jd** [comment]
You mean there's nothing on http://localhost:8000/ ?

**Comment by vonpupp** [comment]
Only an HTML listing,

You can find a screenshot [here](https://www.dropbox.com/s/tacwv0g2yl9v7f7/hyde-julien.png?dl=0). Perhaps is a dumb mistake that I'm doing but I don't know what is going on.

**Comment by jd** [comment]
For some reasons the HTML files are not rendered, this is weird. Do you have jinja2 installed?

**Comment by vonpupp** [comment]
Yes I do, I installed from your requirements file, here is the dump of my pip freeze:

```
(.julien2)[av:~/hyde-test/julien.danjou.info]$ pip freeze                                                                                                                                                                            (master✱) 
commando==1.0.0
fswrap==1.0.0
hyde==0.8.9a0
Jinja2==2.7.3
Markdown==2.6.2
MarkupSafe==0.23
Pygments==2.0.2
PyYAML==3.11
smartypants==1.8.6
typogrify==2.0.7
wheel==0.24.0
```

**Comment by jd** [comment]
Ok I just understood… It works, it just that there's no index.html at the root dir because there'a an htaccess that redirects to /blog/. So that's "normal", the Python HTTP server does not handle .htacces files obviously, and the site is made to be served by Apache in production. So just open a page like /blog/ and it'll be fine!

**Comment by vonpupp** [comment]
Thank you very much for your help Julien, it works fine =)

WBR,
Albert.
